- hosts: localhost
  connection: local
  pre_tasks:
    - name: Update homebrew
      homebrew:
        update_homebrew: yes

    - name: Install git
      homebrew:
        name: git
        state: latest
  roles:
    - role: casks
      casks_to_install:
        - name: google-chrome
          install_path: /Applications/Google Chrome.app
        - name: firefox
          install_path: /Applications/Firefox.app
        - name: slack
          install_path: /Applications/Slack.app
        - name: docker
          install_path: /Applications/Docker.app
    - role: homebrew
      brew_packages_to_install:
        - node
        - macvim
        - jq
        - couchdb
        - hub
    - role: taps
      taps:
        - name: ravenac95/sudolikeaboss
          packages:
            - sudolikeaboss
    - role: node-packages
      node_packages_to_install:
        - n
        - nesh
        - grunt-cli
